### PR TITLE
Add graphic to tag types that can exist in a paragraph

### PR DESCRIPTION
**Pull request by ascott1**
As advertised.

This also trims any left over trailing white space, because my editor is configured to do that.

### CODE REVIEW

**Comment by willbarton** [comment]
> This also trims any left over trailing white space, because my editor is configured to do that.

So you'll `git blame`d for those lines 😜

**Comment by ascott1** [comment]
> So you'll git blamed for those lines 😜

D'oh. I better start a collection of "I didn't do it" gifs as a safeguard.

**Comment by willbarton** [comment]
We'll make a pythonista of you yet.

**Comment by ascott1** [comment]
I write my best Python code when you tell me exactly what to do @willbarton.

**Pull request merged**
